# Generated by Django 4.2.27 on 2026-01-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field_3',
        ),
    ]
